//          EXERCISE
// RECEBA UM ARRAY DE 5 VALORES INTEIROS 
// REALIZE A SOMA DOS 4 MAIORES VALORES
// REALIZE A SOMA DOS 4 MENORES VALORES
// MOSTRE O RESULTADO DAS DUAS SOMAS

const arg = [5, 8, 6, 7];


const sumMaxMin = (arg) => {

}

sumMaxMin(arg);